### ISSUE TITLE
font bug(fim dash script)

### ISSUE THREAD

**Issue by coldtoon** [Inrixia/inrixia.github.io#1]
there is a font bug causing some font to be of lighter color making it close to unreadable: [https://imgur.com/a/gshZP](url) even to th point where whole stories are like this: [https://imgur.com/a/laAoR](url)

**Comment by coldtoon** [comment]
links are not working from hyper link you are going to have to copy and paste them

**Comment by Inrixia** [comment]
I'll fix it with the updates I'm putting out tomorrow. Happy New year and gnight :)

**Comment by coldtoon** [comment]
thank you

**Comment by Inrixia** [comment]
Fixed now along with a few other updates related to the new css. Thanks for bringing it up. I read with the dark setting anyway so I wouldn't have noticed it. @coldtoon 

You should just be able to refresh the page to get the new css.

**Comment by coldtoon** [comment]
glad i could help

**Comment by coldtoon** [comment]
ohh nice update ^.^ https://imgur.com/a/mO3qW ......................is this a bug? https://imgur.com/a/EEzSD

**Comment by Inrixia** [comment]
https://imgur.com/a/mO3qW isn't a bug as far as I know. That's just how next chapter is done with the dark theme though I might consider making it darker. The second I can probably fix to just use Fimfictions default so it isn't black on white but still works for a dark mode. I'll sort it a bit later. 

#Edit
I missed the circles in the images because I was browsing on my phone and thought that you were referring to the color as a issue in both. But yes the 2nd image is a bug and how now been fixed. I just didn't read the images properly before posting this comment :P

**Comment by Inrixia** [comment]
Fixed. Made it slightly darker and fixed the color not showing. Also fixed the drop down for multiple chapters.

I cant make it white as there is no way to have it change color depending on the theme you set on the site and I expect most people to be reading with a dark setting anyway. Plus dark looks pretty ok with the white anyway. Also if you didn't know you can have the background for reading be dark if you change it in the formatting tab.

Thanks again for bringing this to my attention :).
